=== nodelook/data/.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "title": "NodeLook Group",
  "description": "Schema for NodeLook Android data group files",
  "type": "object",
  "required": [
    "name",
    "description",
    "color",
    "items"
  ],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "name": {
      "description": "The display name of the group",
      "$ref": "#/definitions/localizedString"
    },
    "description": {
      "description": "A short description of the group",
      "$ref": "#/definitions/localizedString"
    },
    "color": {
      "description": "ARGB hex color code for the group (e.g. #FF4285F4)",
      "type": "string",
      "pattern": "^#[0-9A-Fa-f]{8}$"
    },
    "items": {
      "description": "List of services/endpoints to check",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/item"
      }
    }
  },
  "definitions": {
    "localizedString": {
      "type": "object",
      "required": [
        "en",
        "fa"
      ],
      "additionalProperties": false,
      "properties": {
        "en": {
          "type": "string",
          "minLength": 1,
          "description": "English text"
        },
        "fa": {
          "type": "string",
          "minLength": 1,
          "description": "Persian text"
        }
      }
    },
    "item": {
      "type": "object",
      "required": [
        "name",
        "url",
        "shouldContain",
        "address"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "description": "Display name of the service or endpoint",
          "$ref": "#/definitions/localizedString"
        },
        "url": {
          "description": "The URL to send a request to",
          "type": "string",
          "format": "uri"
        },
        "shouldContain": {
          "description": "A string that the response body must contain for the check to pass",
          "type": "string",
          "minLength": 1
        },
        "address": {
          "description": "The address to display to the user",
          "type": "string",
          "format": "uri"
        }
      }
    }
  }
}

=== nodelook/data/huggingface.json
{
  "$schema": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "name": {
    "en": "HF",
    "fa": "اچ‌اف"
  },
  "description": {
    "en": "HuggingFace Mirrors\n\nexport HF_ENDPOINT=https://hf-mirror.com",
    "fa": "آینه‌های هاگینگ‌فیس\n\nexport HF_ENDPOINT=https://hf-mirror.com"
  },
  "color": "#FF34A853",
  "items": [
    {
      "name": {
        "en": "Hugging Face",
        "fa": "هاگینگ‌فیس"
      },
      "url": "https://huggingface.co/api/models/Qwen/Qwen3-8B",
      "shouldContain": "Qwen/Qwen3-8B",
      "address": "https://huggingface.co"
    },
    {
      "name": {
        "en": "[China] HF Mirror",
        "fa": "[چین] آینه‌های اچ‌اف"
      },
      "url": "https://hf-mirror.com/api/models/Qwen/Qwen3-8B",
      "shouldContain": "Qwen/Qwen3-8B",
      "address": "https://hf-mirror.com"
    },
    {
      "name": {
        "en": "[Iran] Parmin Cloud",
        "fa": "[ایران] ابر پارمین"
      },
      "url": "https://huggingface.parmincloud.ir/api/models/Qwen/Qwen3-8B",
      "shouldContain": "Qwen/Qwen3-8B",
      "address": "https://huggingface.parmincloud.ir"
    },
    {
      "name": {
        "en": "[Iran] Rasanegaar",
        "fa": "[ایران] رسانگار"
      },
      "url": "https://mirror.rasanegaar.com/hf/api/models/Qwen/Qwen3-8B",
      "shouldContain": "Qwen/Qwen3-8B",
      "address": "https://mirror.rasanegaar.com/hf"
    }
  ]
}

=== nodelook/data/matrix.json
{
  "$schema": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "name": {
    "en": "Matrix",
    "fa": "ماتریکس"
  },
  "description": {
    "en": "Matrix Servers",
    "fa": "کارسازهای ماتریکس"
  },
  "color": "#FF4285F4",
  "items": [
    {
      "name": {
        "en": "[United States] Secure Channel",
        "fa": "[ایالات متحده] کانال امن"
      },
      "url": "https://secure-channel.net/_matrix/client/versions",
      "shouldContain": "io.element.e2ee_forced.trusted_private",
      "address": "https://secure-channel.net/"
    },
    {
      "name": {
        "en": "[Canada] SK Community",
        "fa": "[کانادا] انجمن اس‌کا"
      },
      "url": "https://sk.community/_matrix/client/versions",
      "shouldContain": "io.element.e2ee_forced.trusted_private",
      "address": "https://sk.community/"
    },
    {
      "name": {
        "en": "[Germany] Rollenspiel",
        "fa": "[آلمان] نقش‌آفرینی"
      },
      "url": "https://rollenspiel.chat/_matrix/client/versions",
      "shouldContain": "io.element.e2ee_forced.trusted_private",
      "address": "https://rollenspiel.chat/"
    },
    {
      "name": {
        "en": "[Germany] Quassel",
        "fa": "[آلمان] کواسل"
      },
      "url": "https://quassel.io/_matrix/client/versions",
      "shouldContain": "io.element.e2ee_forced.trusted_private",
      "address": "https://quassel.io/"
    },
    {
      "name": {
        "en": "[Germany] Magdeburg",
        "fa": "[آلمان] ماگدبورگ"
      },
      "url": "https://magdeburg.jetzt/_matrix/client/versions",
      "shouldContain": "io.element.e2ee_forced.trusted_private",
      "address": "https://magdeburg.jetzt/"
    },
    {
      "name": {
        "en": "[China] Hashi",
        "fa": "[چین] هاشی"
      },
      "url": "https://hashi.sbs/_matrix/client/versions",
      "shouldContain": "io.element.e2ee_forced.trusted_private",
      "address": "https://hashi.sbs/"
    }
  ]
}

=== nodelook/data/vcs.json
{
  "$schema": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "name": {
    "en": "Code",
    "fa": "کد"
  },
  "description": {
    "en": "Version Control Systems",
    "fa": "سیستم‌های کنترل نسخه"
  },
  "color": "#FF4285F4",
  "items": [
    {
      "name": {
        "en": "GitHub Site",
        "fa": "سایت گیت‌هاب"
      },
      "url": "https://github.com/xmha97/test/blob/main/test",
      "shouldContain": "thegithubsiteisworkingproperly",
      "address": "https://"
    },
    {
      "name": {
        "en": "GitHub API",
        "fa": "ای‌پی‌آی گیت‌هاب"
      },
      "url": "https://api.github.com/octocat?s=thegithubapiisworkingproperly",
      "shouldContain": "thegithubapiisworkingproperly",
      "address": "https://"
    },
    {
      "name": {
        "en": "GitHub Pages",
        "fa": "صفحه‌های گیت‌هاب"
      },
      "url": "https://xmha97.github.io/status",
      "shouldContain": "200",
      "address": "https://"
    },
    {
      "name": {
        "en": "GitHub Gists",
        "fa": "گیست‌های گیت‌هاب"
      },
      "url": "https://gist.githubusercontent.com/xmha97/94f6ba425d9874179fdd73fc0e2dc899/raw/e3a7ca5109c651f711000b3a02b4e032bd1d695f/status",
      "shouldContain": "200",
      "address": "https://"
    },
    {
      "name": {
        "en": "GitHub Repository",
        "fa": "مخزن گیت‌هاب"
      },
      "url": "https://raw.githubusercontent.com/xmha97/test/refs/heads/main/status",
      "shouldContain": "200",
      "address": "https://"
    },
    {
      "name": {
        "en": "GitHub Releases",
        "fa": "رهانش‌های گیت‌هاب"
      },
      "url": "https://github.com/xmha97/test/releases/download/v1.0.0/status",
      "shouldContain": "200",
      "address": "https://"
    },
    {
      "name": {
        "en": "GitHub App",
        "fa": "اپ گیت‌هاب"
      },
      "url": "https://githubapp.com",
      "shouldContain": "OK",
      "address": "https://"
    },
    {
      "name": {
        "en": "Codeberg Repository",
        "fa": "مخزن کدبرگ"
      },
      "url": "https://codeberg.org/xmha97/test/raw/branch/main/status",
      "shouldContain": "200",
      "address": "https://"
    },
    {
      "name": {
        "en": "Codeberg Releases",
        "fa": "رهانش‌های کدبرگ"
      },
      "url": "https://codeberg.org/xmha97/test/releases/download/v1.0.0/status",
      "shouldContain": "200",
      "address": "https://"
    },
    {
      "name": {
        "en": "GitLab",
        "fa": "گیت‌لب"
      },
      "url": "https://gitlab.com/xmha97/test/-/raw/master/status",
      "shouldContain": "200",
      "address": "https://"
    },
    {
      "name": {
        "en": "[Iran] HamGit (GitLab)",
        "fa": "هم‌گیت (گیت‌لب) [ایران]"
      },
      "url": "https://hamgit.ir/xmha97/test/-/raw/main/status",
      "shouldContain": "200",
      "address": "https://"
    },
    {
      "name": {
        "en": "[Iran] AranServer (GitLab)",
        "fa": "آران‌سرور (گیت‌لب) [ایران]"
      },
      "url": "https://gitlab.aranserver.com/xmha97/test/-/raw/main/status",
      "shouldContain": "200",
      "address": "https://"
    },
    {
      "name": {
        "en": "[Iran] Fandak (Gitea)",
        "fa": "فندک (گیتی) [ایران]"
      },
      "url": "https://gitea.fandak.lol/xmha97/test/raw/branch/main/status",
      "shouldContain": "200",
      "address": "https://"
    },
    {
      "name": {
        "en": "[Iran] Mred (Gitea)",
        "fa": "ام‌رد (گیتی) [ایران]"
      },
      "url": "https://git.mred.ir/xmha97/test/raw/branch/main/status",
      "shouldContain": "200",
      "address": "https://"
    }
  ]
}

=== nodelook/data/githubrelease.json
{
  "$schema": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "name": {
    "en": "GH Rel",
    "fa": "رها گ‌ه"
  },
  "description": {
    "en": "GitHub Release Mirrors",
    "fa": "آینه‌های رهانش گیت‌هاب"
  },
  "color": "#FF4285F4",
  "items": [
    {
      "name": {
        "en": "GitHub",
        "fa": "گیت‌هاب"
      },
      "url": "https://github.com/xmha97/test/releases/download/v1.0.0/status",
      "shouldContain": "200",
      "address": "https://github.com/<owner>/<repo>/releases/download/<tag>/<asset>"
    },
    {
      "name": {
        "en": "Statically",
        "fa": "استاتیکالی"
      },
      "url": "https://cdn.statically.io/gh/xmha97/test@v1.0.0/status",
      "shouldContain": "200",
      "address": "https://cdn.statically.io/gh/<owner>/<repo>@<tag>/<asset>"
    },
    {
      "name": {
        "en": "jsDelivr",
        "fa": "جی‌اس‌دلیور"
      },
      "url": "https://cdn.jsdelivr.net/gh/xmha97/test@v1.0.0/status",
      "shouldContain": "200",
      "address": "https://cdn.jsdelivr.net/gh/<owner>/<repo>@<tag>/<asset>"
    },
    {
      "name": {
        "en": "jsdMirror",
        "fa": "جی‌اس‌دی‌میرور"
      },
      "url": "https://cdn.jsdmirror.com/gh/xmha97/test@v1.0.0/status",
      "shouldContain": "200",
      "address": "https://cdn.jsdmirror.com/gh/<owner>/<repo>@<tag>/<asset>"
    },
    {
      "name": {
        "en": "gh-Proxy",
        "fa": "جی‌اچ-پروکسی"
      },
      "url": "https://gh-proxy.org/https://github.com/xmha97/test/releases/download/v1.0.0/status",
      "shouldContain": "200",
      "address": "https://gh-proxy.org/https://github.com/<owner>/<repo>/releases/download/<tag>/<asset>"
    },
    {
      "name": {
        "en": "ghProxy",
        "fa": "جی‌اچ‌پروکسی"
      },
      "url": "https://ghproxy.net/https://github.com/xmha97/test/releases/download/v1.0.0/status",
      "shouldContain": "200",
      "address": "https://ghproxy.net/https://github.com/<owner>/<repo>/releases/download/<tag>/<asset>"
    },
    {
      "name": {
        "en": "proxy.gitwarp",
        "fa": "proxy.gitwarp"
      },
      "url": "https://proxy.gitwarp.com/https://github.com/xmha97/test/releases/download/v1.0.0/status",
      "shouldContain": "200",
      "address": "https://proxy.gitwarp.com/https://github.com/<owner>/<repo>/releases/download/<tag>/<asset>"
    },
    {
      "name": {
        "en": "ghfast",
        "fa": "ghfast"
      },
      "url": "https://ghfast.top/https://github.com/xmha97/test/releases/download/v1.0.0/status",
      "shouldContain": "200",
      "address": "https://ghfast.top/https://github.com/<owner>/<repo>/releases/download/<tag>/<asset>"
    },
    {
      "name": {
        "en": "github.mxw.qzz",
        "fa": "github.mxw.qzz"
      },
      "url": "https://github.mxw.qzz.io/https://github.com/xmha97/test/releases/download/v1.0.0/status",
      "shouldContain": "200",
      "address": "https://github.mxw.qzz.io/https://github.com/<owner>/<repo>/releases/download/<tag>/<asset>"
    },
    {
      "name": {
        "en": "down.mxw.qzz",
        "fa": "down.mxw.qzz"
      },
      "url": "https://down.mxw.qzz.io/https://github.com/xmha97/test/releases/download/v1.0.0/status",
      "shouldContain": "200",
      "address": "https://down.mxw.qzz.io/https://github.com/<owner>/<repo>/releases/download/<tag>/<asset>"
    },
    {
      "name": {
        "en": "[Iran] Azizi",
        "fa": "[عزیزی] عزیزی"
      },
      "url": "    https://gitdl.theazizi.ir/https%3A%2F%2Fgithub.com%2Fxmha97%2Ftest%2Freleases%2Fdownload%2Fv1.0.0%2Fstatus",
      "shouldContain": "200",
      "address": "https://gitdl.theazizi.ir/https%3A%2F%2Fgithub.com%2F<owner>%2F<repo>%2Freleases%2Fdownload%2F<tag>%2F<asset>"
    }
  ]
}

=== nodelook/data/family.json
{
  "$schema": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "name": {
    "en": "Family",
    "fa": "خانواده"
  },
  "description": {
    "en": "Adult Content Filtering\nTests whether your DNS or network blocks adult-content websites.\n\n# Cloudflare Family\nIPv4: 1.1.1.3\nIPv4: 1.0.0.3\nIPv6: 2606:4700:4700::1113\nIPv6: 2606:4700:4700::1003\n\n# CleanBrowsing – Family Filter\nIPv4: 185.228.168.168\nIPv4: 185.228.169.168\nIPv6: 2a0d:2a00:1::\nIPv6: 2a0d:2a00:2::\n\n# AdGuard Family Protection\nIPv4: 94.140.14.15\nIPv4: 94.140.15.16\nIPv6: 2a10:50c0::bad1:ff\nIPv6: 2a10:50c0::bad2:ff\n\nSUCCESS: age verification is disabled",
    "fa": "فیلتر محتوای بزرگسال\nبررسی می‌کند که آیا دی‌ان‌اس یا شبکه‌ی شما وب‌سایت‌های دارای محتوای بزرگسال را مسدود می‌کند یا خیر.\n\n# Cloudflare Family\nIPv4: 1.1.1.3\nIPv4: 1.0.0.3\nIPv6: 2606:4700:4700::1113\nIPv6: 2606:4700:4700::1003\n\n# CleanBrowsing – Family Filter\nIPv4: 185.228.168.168\nIPv4: 185.228.169.168\nIPv6: 2a0d:2a00:1::\nIPv6: 2a0d:2a00:2::\n\n# AdGuard Family Protection\nIPv4: 94.140.14.15\nIPv4: 94.140.15.16\nIPv6: 2a10:50c0::bad1:ff\nIPv6: 2a10:50c0::bad2:ff\n\nموفقیت: احراز سن غیرفعال است"
  },
  "color": "#FF4285F4",
  "items": [
    {
      "name": {
        "en": "PornHub",
        "fa": "ردیت"
      },
      "url": "https://www.pornhub.com/api/v1/video/ajax_related_video",
      "shouldContain": "Success!",
      "address": "https://www.pornhub.com/"
    }
  ]
}

=== nodelook/data/ytinvidious.json
{
  "$schema": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "name": {
    "en": "YT I",
    "fa": "ی‌ت ا"
  },
  "description": {
    "en": "YouTube Invidious Instances",
    "fa": "نمونه‌های اینویدیوس یوتیوب"
  },
  "color": "#FF4285F4",
  "items": [
    {
      "name": {
        "en": "76.82.152.76",
        "fa": "76.82.152.76"
      },
      "url": "http://76.82.152.76:3000/api/v1/stats",
      "shouldContain": "invidious",
      "address": "http://76.82.152.76:3000"
    },
    {
      "name": {
        "en": "theawaybox",
        "fa": "theawaybox"
      },
      "url": "http://bris.theawaybox.com:3000/api/v1/stats",
      "shouldContain": "invidious",
      "address": "http://bris.theawaybox.com:3000"
    },
    {
      "name": {
        "en": "115.73.217.239",
        "fa": "115.73.217.239"
      },
      "url": "http://115.73.217.239:3000/api/v1/stats",
      "shouldContain": "invidious",
      "address": "http://115.73.217.239:3000"
    },
    {
      "name": {
        "en": "71.115.211.25",
        "fa": "71.115.211.25"
      },
      "url": "http://71.115.211.25:3000/api/v1/stats",
      "shouldContain": "invidious",
      "address": "http://71.115.211.25:3000"
    },
    {
      "name": {
        "en": "146.71.85.119",
        "fa": "146.71.85.119"
      },
      "url": "http://146.71.85.119:14120/api/v1/stats",
      "shouldContain": "invidious",
      "address": "http://146.71.85.119:14120"
    },
    {
      "name": {
        "en": "157.254.18.46",
        "fa": "157.254.18.46"
      },
      "url": "http://157.254.18.46:14120/api/v1/stats",
      "shouldContain": "invidious",
      "address": "http://157.254.18.46:14120"
    },
    {
      "name": {
        "en": "45.51.2.189",
        "fa": "45.51.2.189"
      },
      "url": "http://45.51.2.189:1337/api/v1/stats",
      "shouldContain": "invidious",
      "address": "http://45.51.2.189:1337"
    },
    {
      "name": {
        "en": "83.195.54.144",
        "fa": "83.195.54.144"
      },
      "url": "http://83.195.54.144:9876/api/v1/stats",
      "shouldContain": "invidious",
      "address": "http://83.195.54.144:9876"
    },
    {
      "name": {
        "en": "kronickrusaders",
        "fa": "kronickrusaders"
      },
      "url": "http://tube.kronickrusaders.ca:6666/api/v1/stats",
      "shouldContain": "invidious",
      "address": "http://tube.kronickrusaders.ca:6666"
    },
    {
      "name": {
        "en": "51.91.122.148",
        "fa": "51.91.122.148"
      },
      "url": "http://51.91.122.148:3000/api/v1/stats",
      "shouldContain": "invidious",
      "address": "http://51.91.122.148:3000"
    }
  ]
}

=== nodelook/data/libgen.json
{
  "$schema": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "name": {
    "en": "LibGen",
    "fa": "لیب‌جن"
  },
  "description": {
    "en": "Library Genesis",
    "fa": "کتابخانه جنسیس"
  },
  "color": "#FF34A853",
  "items": [
    {
      "name": {
        "en": "Belize Domain",
        "fa": "دامنه‌ی بلیز"
      },
      "url": "https://libgen.bz/js/form-validation.js",
      "shouldContain": "was-validated",
      "address": "https://libgen.bz/"
    },
    {
      "name": {
        "en": "Estonia Domain",
        "fa": "دامنه‌ی استونی"
      },
      "url": "https://libgen.ee/js/form-validation.js",
      "shouldContain": "was-validated",
      "address": "https://libgen.ee/"
    },
    {
      "name": {
        "en": "Greenland Domain",
        "fa": "دامنه‌ی گرینلند"
      },
      "url": "https://libgen.gl/js/form-validation.js",
      "shouldContain": "was-validated",
      "address": "https://libgen.gl/"
    },
    {
      "name": {
        "en": "Laos Domain",
        "fa": "دامنه‌ی لائوس"
      },
      "url": "https://libgen.la/js/form-validation.js",
      "shouldContain": "was-validated",
      "address": "https://libgen.la/"
    },
    {
      "name": {
        "en": "Liechtenstein Domain",
        "fa": "دامنه‌ی لیختن‌اشتاین"
      },
      "url": "https://libgen.li/js/form-validation.js",
      "shouldContain": "was-validated",
      "address": "https://libgen.bz/"
    },
    {
      "name": {
        "en": "British Virgin Islands Domain",
        "fa": "دامنه‌ی جزایر ویرجین بریتانیا"
      },
      "url": "https://libgen.vg/js/form-validation.js",
      "shouldContain": "was-validated",
      "address": "https://libgen.vg/"
    }
  ]
}

=== nodelook/data/ytapilegacy.json
{
  "$schema": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "name": {
    "en": "YT A",
    "fa": "ی‌ت ا"
  },
  "description": {
    "en": "YouTube API Legacy Instances",
    "fa": "نمونه‌های ای‌پی‌آی قدیمی یوتیوب"
  },
  "color": "#FF4285F4",
  "items": [
    {
      "name": {
        "en": "45.132.96.44",
        "fa": "45.132.96.44"
      },
      "url": "http://193.124.118.227/download",
      "shouldContain": "YouTube",
      "address": "http://45.132.96.44:2823"
    }
  ]
}
