=== nodelook/data/.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "title": "NodeLook Group",
  "description": "Schema for NodeLook Android data group files",
  "type": "object",
  "required": [
    "name",
    "description",
    "color",
    "items"
  ],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string",
      "format": "uri"
    },
    "name": {
      "description": "The display name of the group",
      "$ref": "#/definitions/localizedString"
    },
    "description": {
      "description": "A short description of the group",
      "$ref": "#/definitions/localizedString"
    },
    "color": {
      "description": "ARGB hex color code for the group (e.g. #FF4285F4)",
      "type": "string",
      "pattern": "^#[0-9A-Fa-f]{8}$"
    },
    "items": {
      "description": "List of services/endpoints to check",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/item"
      }
    }
  },
  "definitions": {
    "localizedString": {
      "type": "object",
      "required": [
        "en",
        "fa"
      ],
      "additionalProperties": false,
      "properties": {
        "en": {
          "type": "string",
          "minLength": 1,
          "description": "English text"
        },
        "fa": {
          "type": "string",
          "minLength": 1,
          "description": "Persian text"
        }
      }
    },
    "item": {
      "type": "object",
      "required": [
        "name",
        "url",
        "shouldContain",
        "address"
      ],
      "additionalProperties": false,
      "properties": {
        "name": {
          "description": "Display name of the service or endpoint",
          "$ref": "#/definitions/localizedString"
        },
        "url": {
          "description": "The URL to send a request to",
          "type": "string",
          "format": "uri"
        },
        "shouldContain": {
          "description": "A string that the response body must contain for the check to pass",
          "type": "string",
          "minLength": 1
        },
        "address": {
          "description": "The address to display to the user",
          "type": "string",
          "format": "uri"
        }
      }
    }
  }
}

=== nodelook/data/ytpiped.json
{
  "$schema": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "name": {
    "en": "YT P",
    "fa": "ی‌ت ل"
  },
  "description": {
    "en": "YouTube Piped Instances",
    "fa": "نمونه‌های لوله‌کشی‌شده یوتیوب"
  },
  "color": "#FF4285F4",
  "items": [
    {
      "name": {
        "en": "51.154.9.70:8081",
        "fa": "51.154.9.70:8081"
      },
      "url": "http://51.154.9.70:8081/healthcheck",
      "shouldContain": "OK",
      "address": "http://51.154.9.70:8081"
    },
    {
      "name": {
        "en": "51.154.9.70:8082",
        "fa": "51.154.9.70:8082"
      },
      "url": "http://51.154.9.70:8082/healthcheck",
      "shouldContain": "OK",
      "address": "http://51.154.9.70:8082"
    },
    {
      "name": {
        "en": "130.12.171.163:8081",
        "fa": "130.12.171.163:8081"
      },
      "url": "http://130.12.171.163:8081/healthcheck",
      "shouldContain": "OK",
      "address": "http://130.12.171.163:8081"
    },
    {
      "name": {
        "en": "130.12.171.163:8082",
        "fa": "130.12.171.163:8082"
      },
      "url": "http://130.12.171.163:8082/healthcheck",
      "shouldContain": "OK",
      "address": "http://130.12.171.163:8082"
    },
    {
      "name": {
        "en": "77.110.101.50:8081",
        "fa": "77.110.101.50:8081"
      },
      "url": "http://77.110.101.50:8081/healthcheck",
      "shouldContain": "OK",
      "address": "http://77.110.101.50:8081"
    },
    {
      "name": {
        "en": "77.110.101.50:8082",
        "fa": "77.110.101.50:8082"
      },
      "url": "http://77.110.101.50:8082/healthcheck",
      "shouldContain": "OK",
      "address": "http://77.110.101.50:8082"
    },
    {
      "name": {
        "en": "82.24.19.217:8084",
        "fa": "82.24.19.217:8084"
      },
      "url": "http://82.24.19.217:8084/healthcheck",
      "shouldContain": "OK",
      "address": "http://82.24.19.217:8084"
    },
    {
      "name": {
        "en": "82.24.19.217:8085",
        "fa": "82.24.19.217:8085"
      },
      "url": "http://82.24.19.217:8085/healthcheck",
      "shouldContain": "OK",
      "address": "http://82.24.19.217:8085"
    },
    {
      "name": {
        "en": "124.158.10.214:8081",
        "fa": "124.158.10.214:8081"
      },
      "url": "http://124.158.10.214:8081/healthcheck",
      "shouldContain": "OK",
      "address": "http://124.158.10.214:8081"
    },
    {
      "name": {
        "en": "124.158.10.214:8383",
        "fa": "124.158.10.214:8383"
      },
      "url": "http://124.158.10.214:8383/healthcheck",
      "shouldContain": "OK",
      "address": "http://124.158.10.214:8383"
    },
    {
      "name": {
        "en": "167.114.169.34:8081",
        "fa": "167.114.169.34:8081"
      },
      "url": "http://167.114.169.34:8081/healthcheck",
      "shouldContain": "OK",
      "address": "http://167.114.169.34:8081"
    },
    {
      "name": {
        "en": "167.114.169.34:8082",
        "fa": "167.114.169.34:8082"
      },
      "url": "http://167.114.169.34:8082/healthcheck",
      "shouldContain": "OK",
      "address": "http://167.114.169.34:8082"
    }
  ]
}

=== nodelook/data/google.json
{
  "$schema": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "name": {
    "en": "Google",
    "fa": "گوگل"
  },
  "description": {
    "en": "Google Video Transport",
    "fa": "انتقال ویدئوی گوگل"
  },
  "color": "#FF34A853",
  "items": [
    {
      "name": {
        "en": "EdgeDL",
        "fa": "اج‌دی‌ال"
      },
      "url": "https://edgedl.me.gvt1.com/robots.txt",
      "shouldContain": "Disallow",
      "address": "https://edgedl.me.gvt1.com/"
    },
    {
      "name": {
        "en": "Redirector",
        "fa": "تغییردهنده‌ی‌مسیر"
      },
      "url": "https://redirector.gvt1.com/edgedl/robots.txt",
      "shouldContain": "Disallow",
      "address": "https://redirector.gvt1.com/"
    },
    {
      "name": {
        "en": "Server 1",
        "fa": "کارساز ۱"
      },
      "url": "https://r1---sn-5hne6nsk.gvt1.com/edgedl/robots.txt",
      "shouldContain": "Disallow",
      "address": "https://r1---sn-5hne6nsk.gvt1.com/"
    },
    {
      "name": {
        "en": "Server 2",
        "fa": "کارساز ۲"
      },
      "url": "https://r2---sn-5hne6nsr.gvt1.com/edgedl/robots.txt",
      "shouldContain": "Disallow",
      "address": "https://r2---sn-5hne6nsr.gvt1.com/"
    },
    {
      "name": {
        "en": "Server 3",
        "fa": "کارساز ۳"
      },
      "url": "https://r3---sn-nv47lns7.gvt1.com/edgedl/robots.txt",
      "shouldContain": "Disallow",
      "address": "https://r3---sn-nv47lns7.gvt1.com/"
    },
    {
      "name": {
        "en": "Server 4",
        "fa": "کارساز ۴"
      },
      "url": "https://r4---sn-5hnekn76.gvt1.com/edgedl/robots.txt",
      "shouldContain": "Disallow",
      "address": "https://r4---sn-5hnekn76.gvt1.com/"
    }
  ]
}

=== nodelook/data/internet.json
{
  "$schema": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "name": {
    "en": "Internet",
    "fa": "اینترنت"
  },
  "description": {
    "en": "Internet",
    "fa": "اینترنت"
  },
  "color": "#FF4285F4",
  "items": [
    {
      "name": {
        "en": "Irancell",
        "fa": "ایرانسل"
      },
      "url": "https://insufficient.irancell.ir/",
      "shouldContain": "به پایان رسیده است",
      "address": "https://irancell.ir/"
    },
    {
      "name": {
        "en": "IR-MCI",
        "fa": "همراه‌اول"
      },
      "url": "https://mci.ir/robots.txt",
      "shouldContain": "Disallow",
      "address": "https://mci.ir/"
    }
  ]
}

=== nodelook/data/julia.json
{
  "$schema": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "name": {
    "en": "Julia",
    "fa": "جولیا"
  },
  "description": {
    "en": "Julia Mirrors",
    "fa": "آینه‌های جولیا"
  },
  "color": "#FF34A853",
  "items": [
    {
      "name": {
        "en": "Julia",
        "fa": "جولیا"
      },
      "url": "https://eu-central.pkg.julialang.org/registries.conservative",
      "shouldContain": "/registry/",
      "address": "https://"
    },
    {
      "name": {
        "en": "[China] Tsinghua University",
        "fa": "[چین] دانشگاه تسینگ‌هوا"
      },
      "url": "https://mirrors.tuna.tsinghua.edu.cn/julia/registries.conservative",
      "shouldContain": "/registry/",
      "address": "https://"
    },
    {
      "name": {
        "en": "[China] University of Science and Technology of China",
        "fa": "[چین] دانشگاه علم و فناوری چین"
      },
      "url": "https://mirrors.ustc.edu.cn/julia/registries.conservative",
      "shouldContain": "/registry/",
      "address": "https://"
    },
    {
      "name": {
        "en": "[China] Beijing Foreign Studies University",
        "fa": "[چین] دانشگاه مطالعات خارجی پکن"
      },
      "url": "https://mirrors.bfsu.edu.cn/julia/registries.conservative",
      "shouldContain": "/registry/",
      "address": "https://"
    },
    {
      "name": {
        "en": "[China] Shanghai Jiao Tong University",
        "fa": "[چین] دانشگاه شانگهای جیائو تونگ"
      },
      "url": "https://mirrors.sjtug.sjtu.edu.cn/julia/registries.conservative",
      "shouldContain": "/registry/",
      "address": "https://"
    },
    {
      "name": {
        "en": "[China] Nanjing University (HTTP)",
        "fa": "[چین] دانشگاه نانجینگ (اچ‌تی‌تی‌پی)"
      },
      "url": "https://mirror.nju.edu.cn/julia/registries.conservative",
      "shouldContain": "/registry/",
      "address": "https://"
    },
    {
      "name": {
        "en": "[China] Southern University of Science and Technology",
        "fa": "[چین] دانشگاه علم و فناوری جنوب"
      },
      "url": "https://mirrors.sustech.edu.cn/julia/registries.conservative",
      "shouldContain": "/registry/",
      "address": "https://"
    }
  ]
}

=== nodelook/data/cargo.json
{
  "$schema": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "name": {
    "en": "Cargo",
    "fa": "کارگو"
  },
  "description": {
    "en": "Rust Cargo Registry Sparse Index Mirrors\nnano ~/.cargo/config.toml",
    "fa": "میرورهای اسپارس ایندکس رجیستری کارگو راست\nnano ~/.cargo/config.toml"
  },
  "color": "#FF34A853",
  "items": [
    {
      "name": {
        "en": "Crates",
        "fa": "Crates"
      },
      "url": "https://index.crates.io/config.json",
      "shouldContain": "https://crates.io",
      "address": "https://index.crates.io"
    },
    {
      "name": {
        "en": "[China] Beijing Foreign Studies University (HTTP)",
        "fa": "[چین] (اچ‌تی‌تی‌پی) دانشگاه مطالعات خارجی پکن"
      },
      "url": "http://mirrors.bfsu.edu.cn/crates.io-index/config.json",
      "shouldContain": "https://crates.io",
      "address": "http://mirrors.bfsu.edu.cn"
    },
    {
      "name": {
        "en": "[China] Beijing Foreign Studies University (HTTPS)",
        "fa": "[چین] (اچ‌تی‌تی‌پی‌اس) دانشگاه مطالعات خارجی پکن"
      },
      "url": "https://mirrors.bfsu.edu.cn/crates.io-index/config.json",
      "shouldContain": "https://crates.io",
      "address": "https://mirrors.bfsu.edu.cn"
    },
    {
      "name": {
        "en": "[China] Zhejiang University",
        "fa": "[چین] دانشگاه ژجیانگ"
      },
      "url": "https://mirrors.zju.edu.cn/crates.io-index/config.json",
      "shouldContain": "https://crates.io",
      "address": "https://mirrors.zju.edu.cn"
    },
    {
      "name": {
        "en": "[China] Tsinghua University (HTTP)",
        "fa": "[چین] دانشگاه تسینگ‌هوا (اچ‌تی‌تی‌پی)"
      },
      "url": "http://mirrors.tuna.tsinghua.edu.cn/crates.io-index/config.json",
      "shouldContain": "https://crates.io",
      "address": "http://mirrors.tuna.tsinghua.edu.cn"
    },
    {
      "name": {
        "en": "[China] Tsinghua University (HTTPS)",
        "fa": "[چین] دانشگاه تسینگ‌هوا (اچ‌تی‌تی‌پی‌اس)"
      },
      "url": "https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/config.json",
      "shouldContain": "https://crates.io",
      "address": "https://mirrors.tuna.tsinghua.edu.cn"
    },
    {
      "name": {
        "en": "[China] University of Science and Technology of China (HTTP)",
        "fa": "[چین] دانشگاه علم و فناوری چین (اچ‌تی‌تی‌پی)"
      },
      "url": "http://mirrors.ustc.edu.cn/crates.io-index/config.json",
      "shouldContain": "https://crates.io",
      "address": "http://mirrors.ustc.edu.cn"
    },
    {
      "name": {
        "en": "[China] University of Science and Technology of China (HTTPS)",
        "fa": "[چین] دانشگاه علم و فناوری چین (اچ‌تی‌تی‌پی‌اس)"
      },
      "url": "https://mirrors.ustc.edu.cn/crates.io-index/config.json",
      "shouldContain": "https://crates.io",
      "address": "https://mirrors.ustc.edu.cn"
    }
  ]
}

=== nodelook/data/.veloren.json
{
  "$schema": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "name": {
    "en": "Veloren",
    "fa": "ولورن"
  },
  "description": {
    "en": "Veloren Servers",
    "fa": "کارسازهای ولورن"
  },
  "color": "#FF34A853",
  "items": [
    {
      "name": {
        "en": "[DE] Veloren Project Official Server (EU-1)",
        "fa": "[DE] Veloren Project Official Server (EU-1)"
      },
      "url": "http://server.veloren.net:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[BR] Veloren SA",
        "fa": "[BR] Veloren SA"
      },
      "url": "http://play.veloren.net.br:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[US] HostEZ.io Veloren Community",
        "fa": "[US] HostEZ.io Veloren Community"
      },
      "url": "http://veloren.hostez.io:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[US] Heresy Gaming Veloren",
        "fa": "[US] Heresy Gaming Veloren"
      },
      "url": "http://heresygaming.redirectme.net:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[RU] OGR---Russia-Veloren",
        "fa": "[RU] OGR---Russia-Veloren"
      },
      "url": "http://78.107.237.169:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[AU] The Riotous Rooster Veloren Server",
        "fa": "[AU] The Riotous Rooster Veloren Server"
      },
      "url": "http://riotousrooster.com:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[US] Open Veloren Server - US West",
        "fa": "[US] Open Veloren Server - US West"
      },
      "url": "http://veloren.onlinux.org:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[CL] Pow4Ever.com | Veloren",
        "fa": "[CL] Pow4Ever.com | Veloren"
      },
      "url": "http://veloren.pow4ever.com:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[BR] Realm of Echoes",
        "fa": "[BR] Realm of Echoes"
      },
      "url": "http://kawaiidesu.yukon.ar:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[BR] Veloren na Jamanta",
        "fa": "[BR] Veloren na Jamanta"
      },
      "url": "http://jogar.servidorjamanta.com.br:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[RU] Elbrus e2k server",
        "fa": "[RU] Elbrus e2k server"
      },
      "url": "http://83.102.204.31:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[TR] CRUD Yazılım Veloren Türkiye",
        "fa": "[TR] CRUD Yazılım Veloren Türkiye"
      },
      "url": "http://veloren.crudyazilim.com:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[SG] Endcube",
        "fa": "[SG] Endcube"
      },
      "url": "http://veloren.endcube.net:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[FR] Veloren ES",
        "fa": "[FR] Veloren ES"
      },
      "url": "http://server.veloren.es:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[US] Ravengard (US East)",
        "fa": "[US] Ravengard (US East)"
      },
      "url": "http://play.rvn.gg:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[CL] Aincrad LATAM Network",
        "fa": "[CL] Aincrad LATAM Network"
      },
      "url": "http://veloren.aincradlatam.net:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[US] Veloren WestUS",
        "fa": "[US] Veloren WestUS"
      },
      "url": "http://joeisthebest.mooo.com:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[MX] Veloren Latino",
        "fa": "[MX] Veloren Latino"
      },
      "url": "http://play.velorenla.com:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[CA] Canada Plays Veloren - Skwad Media",
        "fa": "[CA] Canada Plays Veloren - Skwad Media"
      },
      "url": "http://play.skwad.media:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[AU] ShadowGaming-PVP-NEW-200Slots",
        "fa": "[AU] ShadowGaming-PVP-NEW-200Slots"
      },
      "url": "http://1.159.228.1:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[US] konataClub",
        "fa": "[US] konataClub"
      },
      "url": "http://v.konata.club:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[AU] AUS-RASHMELON",
        "fa": "[AU] AUS-RASHMELON"
      },
      "url": "http://aus.rashmelon.com:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[PR] Comunidad Latina",
        "fa": "[PR] Comunidad Latina"
      },
      "url": "http://veloren.prggz.net:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[SE] Sweplox Veloren",
        "fa": "[SE] Sweplox Veloren"
      },
      "url": "http://veloren1.sweplox.net:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[FR] LinuxOS",
        "fa": "[FR] LinuxOS"
      },
      "url": "http://veloren.ynh.ovh:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[FR] Evo-Gaming",
        "fa": "[FR] Evo-Gaming"
      },
      "url": "http://play.evo-gaming.fr:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[KR] Dramatik",
        "fa": "[KR] Dramatik"
      },
      "url": "http://dramatik.me:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[DE] Isse's experimental server",
        "fa": "[DE] Isse's experimental server"
      },
      "url": "http://veloren.isse.rs:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[AR] AETeam Middle East [UAE]",
        "fa": "[AR] AETeam Middle East [UAE]"
      },
      "url": "http://uae.zapto.org:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[DE] PL Stumilowy Las",
        "fa": "[DE] PL Stumilowy Las"
      },
      "url": "http://188.245.171.146:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[SE] Nort-sun",
        "fa": "[SE] Nort-sun"
      },
      "url": "http://game.nort-sun.com:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[DE] EU The Old Guard",
        "fa": "[DE] EU The Old Guard"
      },
      "url": "http://188.40.131.14:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[UA] Nyxthorn Realm",
        "fa": "[UA] Nyxthorn Realm"
      },
      "url": "http://veloren.nyxre.pp.ua:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[AU] Icey's Retro World",
        "fa": "[AU] Icey's Retro World"
      },
      "url": "http://209.25.142.98:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[ES] MxtAppz Veloren Server",
        "fa": "[ES] MxtAppz Veloren Server"
      },
      "url": "http://mxtappz.duckdns.org:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[CN] Veloren Server 维洛伦服务器",
        "fa": "[CN] Veloren Server 维洛伦服务器"
      },
      "url": "http://veloren.hgxds.cn:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[RO] Veloren Romania",
        "fa": "[RO] Veloren Romania"
      },
      "url": "http://velo.inewb.ro:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[CA] QC-FR Azria Gaming - 24/7 - MMO",
        "fa": "[CA] QC-FR Azria Gaming - 24/7 - MMO"
      },
      "url": "http://51.222.110.159:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[PL] Stumilowylas",
        "fa": "[PL] Stumilowylas"
      },
      "url": "http://194.110.4.97:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    },
    {
      "name": {
        "en": "[FR] TeamKit FR — Veloren (EU)",
        "fa": "[FR] TeamKit FR — Veloren (EU)"
      },
      "url": "http://amp.teamkit.fr:14004",
      "shouldContain": "VELOREN",
      "address": "https://"
    }
  ]
}

=== nodelook/data/rubygems.json
{
  "$schema": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "name": {
    "en": "RubyGems",
    "fa": "روبی‌جمز"
  },
  "description": {
    "en": "RubyGems Mirrors\ngem sources --add https://rubygems.org",
    "fa": "آینه‌های روبی‌جمز\ngem sources --add https://rubygems.org"
  },
  "color": "#FF34A853",
  "items": [
    {
      "name": {
        "en": "RubyGems",
        "fa": "روبی‌جمز"
      },
      "url": "https://rubygems.org/api/v1/gems/rails.json",
      "shouldContain": "ruby",
      "address": "https://rubygems.org"
    },
    {
      "name": {
        "en": "Gem Cooperative",
        "fa": "تعاونی جم‌ها"
      },
      "url": "https://gem.coop/api/v1/gems/rails.json",
      "shouldContain": "ruby",
      "address": "https://gem.coop"
    }
  ]
}

=== nodelook/data/detectportal.json
{
  "$schema": "https://raw.githubusercontent.com/nodelook/data/refs/heads/main/.schema.json",
  "name": {
    "en": "Portal",
    "fa": "درگاه"
  },
  "description": {
    "en": "Detect Portal",
    "fa": "تشخیص درگاه"
  },
  "color": "#FF4285F4",
  "items": [
    {
      "name": {
        "en": "Firefox (HTTP)",
        "fa": "فایرفاکس (اچ‌تی‌تی‌پی)"
      },
      "url": "http://detectportal.firefox.com/success.txt",
      "shouldContain": "success",
      "address": "http://detectportal.firefox.com/success.txt"
    },
    {
      "name": {
        "en": "Firefox (HTTPS)",
        "fa": "فایرفاکس (اچ‌تی‌تی‌پی‌اس)"
      },
      "url": "https://detectportal.firefox.com/success.txt",
      "shouldContain": "success",
      "address": "https://detectportal.firefox.com/success.txt"
    },
    {
      "name": {
        "en": "Apple (HTTP)",
        "fa": "اپل (اچ‌تی‌تی‌پی)"
      },
      "url": "http://captive.apple.com/hotspot-detect.html",
      "shouldContain": "Success",
      "address": "http://captive.apple.com/hotspot-detect.html"
    },
    {
      "name": {
        "en": "Apple (HTTPS)",
        "fa": "اپل (اچ‌تی‌تی‌پی‌اس)"
      },
      "url": "https://captive.apple.com/hotspot-detect.html",
      "shouldContain": "Success",
      "address": "https://captive.apple.com/hotspot-detect.html"
    },
    {
      "name": {
        "en": "Apple Old (HTTP)",
        "fa": "اپل قدیمی (اچ‌تی‌تی‌پی)"
      },
      "url": "http://www.apple.com/library/test/success.html",
      "shouldContain": "Success",
      "address": "http://www.apple.com/library/test/success.html"
    },
    {
      "name": {
        "en": "Apple Old (HTTPS)",
        "fa": "اپل قدیمی (اچ‌تی‌تی‌پی‌اس)"
      },
      "url": "https://www.apple.com/library/test/success.html",
      "shouldContain": "Success",
      "address": "https://www.apple.com/library/test/success.html"
    },
    {
      "name": {
        "en": "Microsoft (HTTP)",
        "fa": "ماکروسافت (اچ‌تی‌تی‌پی)"
      },
      "url": "http://www.msftconnecttest.com/connecttest.txt",
      "shouldContain": "Microsoft Connect Test",
      "address": "http://www.msftconnecttest.com/connecttest.txt"
    },
    {
      "name": {
        "en": "Microsoft (HTTPS)",
        "fa": "ماکروسافت (اچ‌تی‌تی‌پی‌اس)"
      },
      "url": "https://www.msftconnecttest.com/connecttest.txt",
      "shouldContain": "Microsoft Connect Test",
      "address": "https://www.msftconnecttest.com/connecttest.txt"
    },
    {
      "name": {
        "en": "Microsoft (HTTP) (IPv6)",
        "fa": "ماکروسافت (اچ‌تی‌تی‌پی) (آی‌پی‌وی۶)"
      },
      "url": "http://ipv6.msftconnecttest.com/connecttest.txt",
      "shouldContain": "Microsoft Connect Test",
      "address": "http://ipv6.msftconnecttest.com/connecttest.txt"
    },
    {
      "name": {
        "en": "Microsoft (HTTPS) (IPv6)",
        "fa": "ماکروسافت (اچ‌تی‌تی‌پی‌اس) (آی‌پی‌وی۶)"
      },
      "url": "https://ipv6.msftconnecttest.com/connecttest.txt",
      "shouldContain": "Microsoft Connect Test",
      "address": "https://ipv6.msftconnecttest.com/connecttest.txt"
    },
    {
      "name": {
        "en": "Microsoft Old (HTTP)",
        "fa": "ماکروسافت قدیمی (اچ‌تی‌تی‌پی)"
      },
      "url": "http://www.msftncsi.com/ncsi.txt",
      "shouldContain": "Microsoft NCSI",
      "address": "http://www.msftncsi.com/ncsi.txt"
    },
    {
      "name": {
        "en": "Microsoft Old (HTTPS)",
        "fa": "ماکروسافت قدیمی (اچ‌تی‌تی‌پی‌اس)"
      },
      "url": "https://www.msftncsi.com/ncsi.txt",
      "shouldContain": "Microsoft NCSI",
      "address": "https://www.msftncsi.com/ncsi.txt"
    },
    {
      "name": {
        "en": "Microsoft Old (HTTP) (IPv6)",
        "fa": "ماکروسافت (اچ‌تی‌تی‌پی) (آی‌پی‌وی۶)"
      },
      "url": "http://ipv6.msftconnecttest.com/connecttest.txt",
      "shouldContain": "Microsoft NCSI",
      "address": "http://ipv6.msftconnecttest.com/connecttest.txt"
    },
    {
      "name": {
        "en": "Microsoft Old (HTTPS) (IPv6)",
        "fa": "ماکروسافت (اچ‌تی‌تی‌پی‌اس) (آی‌پی‌وی۶)"
      },
      "url": "https://ipv6.msftconnecttest.com/connecttest.txt",
      "shouldContain": "Microsoft NCSI",
      "address": "https://ipv6.msftconnecttest.com/connecttest.txt"
    },
    {
      "name": {
        "en": "GNOME (HTTP)",
        "fa": "گنوم (اچ‌تی‌تی‌پی)"
      },
      "url": "http://nmcheck.gnome.org/check_network_status.txt",
      "shouldContain": "NetworkManager is online",
      "address": "http://nmcheck.gnome.org/check_network_status.txt"
    },
    {
      "name": {
        "en": "GNOME (HTTPS)",
        "fa": "گنوم (اچ‌تی‌تی‌پی‌اس)"
      },
      "url": "https://nmcheck.gnome.org/check_network_status.txt",
      "shouldContain": "NetworkManager is online",
      "address": "https://nmcheck.gnome.org/check_network_status.txt"
    },
    {
      "name": {
        "en": "Debian (HTTP)",
        "fa": "دبیان (اچ‌تی‌تی‌پی)"
      },
      "url": "http://network-test.debian.org/nm",
      "shouldContain": "NetworkManager is online",
      "address": "http://network-test.debian.org/nm"
    },
    {
      "name": {
        "en": "Debian (HTTPS)",
        "fa": "دبیان (اچ‌تی‌تی‌پی‌اس)"
      },
      "url": "https://network-test.debian.org/nm",
      "shouldContain": "NetworkManager is online",
      "address": "https://network-test.debian.org/nm"
    },
    {
      "name": {
        "en": "KDE (HTTP)",
        "fa": "کی‌دی‌یی (اچ‌تی‌تی‌پی)"
      },
      "url": "http://networkcheck.kde.org/",
      "shouldContain": "OK",
      "address": "http://networkcheck.kde.org/"
    },
    {
      "name": {
        "en": "KDE (HTTPS)",
        "fa": "کی‌دی‌یی (اچ‌تی‌تی‌پی‌اس)"
      },
      "url": "https://networkcheck.kde.org/",
      "shouldContain": "OK",
      "address": "https://networkcheck.kde.org/"
    }
  ]
}
